version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      mui:
        patterns:
          - "@mui*"
      eslint:
        patterns:
          - "@eslint*"
          - "eslint"
