version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      eslint:
        patterns:
          - "@eslint*"
          - "eslint"
      mui:
        patterns:
          - "@mui*"
      react:
        patterns:
          - "react"
          - "react-dom"
